import type { Metadata } from "next";
import { Inter_Tight, Lora, Fragment_Mono } from "next/font/google";
import "./globals.css";
import Footer from "@/components/shared/Footer/Footer";

const interTight = Inter_Tight({
  variable: "--interTight",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700", "800", "900"],
});

const lora = Lora({
  variable: "--lora",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

const fragmentMono = Fragment_Mono({
  variable: "--fragmentMono",
  subsets: ["latin"],
  weight: ["400"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang='en'
      className={` ${interTight.variable} ${lora.variable} ${fragmentMono.variable}`}
    >
      <body>
        {children}
        <Footer  />
      </body>
    </html>
  );
}
